name: Generate thumbnails
on:
  push:
    branches:
      - main
    paths:
      - 'gallery/*' # Only run on this path changes
jobs:
  generate_thumbnails:
    name: Generate thumbnails
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Should be enough for all runs, GH default is 360 which is unreasonable...
    steps:
      - name: Checkout repository # Check out the repo to access the input image folder.
        uses: actions/checkout@master
      - name: Process Images
        id: images
        uses: subic/ghaction-thumbnails@v1 # Tag number optional, breaking changes not expected.
        with: # Arguments:
          source: 'images' # REQUIRED
          output: 'thumbnails' # REQUIRED
          sizes: 480*296 # REQUIRED
          extensions: 'jpg, jpeg, png, webp, gif, tiff'
          subfolder: '%D'
          filename: '%F'
          fit: 'cover'
          position: 'centre'
          enlarge: 'true'
          overwrite: 'false'
      - name: Commit thumbnail folder # This step will commit generated files, remove if not used as a single purpose workflow. Will exit gracefully if no changes are found.
        run: |
          echo "Committing folder ${{steps.images.outputs.thumbnails}}"
          git config --local user.name "${{github.actor}}"
          git config --local user.email "${{github.actor}}@users.noreply.github.com"
          git add ./${{steps.images.outputs.thumbnails}}" || exit 0
          git commit -m "[skip ci] Auto-generated missing thumbnails" -a || exit 0
          git push -f -q https://${{secrets.TOKEN}}@github.com/${{github.repository}}
