name: Generate thumbnails
on:
  push:
    branches:
      - main
    paths:
      - 'gallery/*' # Only run on this path changes
jobs:
  generate_thumbnails:
    name: Generate thumbnails
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Should be enough for all runs, GH default is 360 which is unreasonable...
    steps:
      - name: Checkout repository # Check out the repo to access the input image folder.
        uses: actions/checkout@master
      - name: Process Images
        id: images
        uses: subic/ghaction-thumbnails@v1 # Tag number optional, breaking changes not expected.
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with: # Arguments:
          source: 'gallery' # REQUIRED
          output: 'thumbnails' # REQUIRED
          sizes: 280 # REQUIRED
          extensions: 'jpg, jpeg, png, webp, gif, tiff'
          subfolder: '%D'
          filename: '%F'
          fit: 'cover'
          position: 'centre'
          enlarge: 'true'
          overwrite: 'true'
      - uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub logo
          default_author: github_actions
